command_timeout = 1000

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$env_var\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[](fg:#33658A)\
"""

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
symbol = "󰸏"
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($profile)(\($region\))]($style)'

[env_var.AWS_ENVIRONMENT]
variable = "AWS_ENVIRONMENT"
symbol = "󰸏 "
style = "fg:#1a1a2e bg:#86BBD8"
format = "[ $symbol $env_value ]($style)"

[env_var.AWS_ENVIRONMENT_ROLE_NAME]
variable = "AWS_ROLE_NAME"
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = "[ $symbol $env_value ]($style)"

[c]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#ffffff bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#1a1a2e bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1a1a2e bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#1a1a2e bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#ffffff bg:#33658A"
format = '[  $time ]($style)'
